---
kind: ConfigMap
apiVersion: v1
metadata:
  name: helm-outdated-config
  namespace: helm-outdated
data:
  SMTP_TO: "example@your-domain.example"
  add_repos.sh: |
    #!/bin/bash
    helm repo add stable https://charts.helm.sh/stable
