---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm-outdated
  namespace: helm-outdated
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: your-storage-class
