---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-outdated
  namespace: helm-outdated
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-outdated-view-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: helm-outdated
  namespace: helm-outdated
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-outdated-secrets
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-outdated-secrets-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-outdated-secrets
subjects:
- kind: ServiceAccount
  name: helm-outdated
  namespace: helm-outdated
